services:
  n8n:
<<<<<<<< HEAD:apps/n8n-zh/2.3.0/docker-compose.yml
    image: n8nio/n8n:2.3.0
========
    image: n8nio/n8n:2.2.2
>>>>>>>> 8e6cc572050a5c9325ed5d40b27a804e3b5f4032:apps/n8n-zh/2.2.2/docker-compose.yml
    container_name: ${CONTAINER_NAME}
    restart: always
    user: 1000:1000
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5678
    volumes:
      - ./data:/home/node/.n8n
      - ./editor-ui:/usr/local/lib/node_modules/n8n/node_modules/n8n-editor-ui/dist
    environment:
      N8N_SECURE_COOKIE: false
      N8N_DEFAULT_LOCALE: zh-CN
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
