on:
  schedule:
  - cron:  "0/1440 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Github Sync
      uses: repo-sync/github-sync@v2.3.0
      with:
        source_repo: "https://github.com/okxlin/appstore.git"
        source_branch: "localApps"
        destination_branch: "okxlin-appstore"
        sync_tags: ""
        github_token: ${{ secrets.PAT }}
